# Exception Handling Enhancement Testing Script
# Tests the global exception handler, correlation IDs, and error response format

param(
    [string]$BaseUrl = "https://localhost:7273",
    [switch]$All,
    [switch]$TestCorrelationId,
    [switch]$TestExceptionMapping,
    [switch]$TestApiResponse,
    [switch]$TestSecurity
)

Write-Host ""
Write-Host "=== Exception Handling Enhancement Testing ===" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor Gray
Write-Host ""

if ($All) {
    $TestCorrelationId = $true
    $TestExceptionMapping = $true
    $TestApiResponse = $true
    $TestSecurity = $true
}

# Test 1: Correlation ID Support
if ($TestCorrelationId) {
    Write-Host "Test 1: Correlation ID Support" -ForegroundColor Yellow
    Write-Host ("=" * 50) -ForegroundColor Gray
    Write-Host ""
    
    # Test with custom correlation ID
    $customCorrelationId = [System.Guid]::NewGuid().ToString()
    Write-Host "Sending request with custom correlation ID: $customCorrelationId" -ForegroundColor Gray
    
    try {
        $headers = @{
            "X-Correlation-ID" = $customCorrelationId
            "Content-Type" = "application/json"
        }
        
        # Make a request that will fail (invalid endpoint)
        $response = Invoke-WebRequest -Uri "$BaseUrl/api/invalid-endpoint" `
            -Method GET `
            -Headers $headers `
            -ErrorAction Stop
        
        Write-Host "   [FAIL] Request should have failed" -ForegroundColor Red
    } catch {
        $httpError = $_.Exception.Response
        if ($httpError) {
            $correlationIdInHeader = $httpError.Headers["X-Correlation-ID"]
            $reader = New-Object System.IO.StreamReader($httpError.GetResponseStream())
            $responseBody = $reader.ReadToEnd()
            $jsonResponse = $responseBody | ConvertFrom-Json
            
            Write-Host "   [OK] Request failed as expected" -ForegroundColor Green
            Write-Host "   Response Status: $($httpError.StatusCode.value__)" -ForegroundColor Gray
            
            if ($correlationIdInHeader) {
                Write-Host "   [OK] Correlation ID in response header: $correlationIdInHeader" -ForegroundColor Green
                if ($correlationIdInHeader -eq $customCorrelationId) {
                    Write-Host "   [OK] Correlation ID matches request!" -ForegroundColor Green
                } else {
                    Write-Host "   [WARN] Correlation ID does not match (may be generated by server)" -ForegroundColor Yellow
                }
            } else {
                Write-Host "   [FAIL] Correlation ID not found in response header" -ForegroundColor Red
            }
            
            if ($jsonResponse.data.correlationId) {
                Write-Host "   [OK] Correlation ID in response body: $($jsonResponse.data.correlationId)" -ForegroundColor Green
            } else {
                Write-Host "   [FAIL] Correlation ID not found in response body" -ForegroundColor Red
            }
        }
    }
    Write-Host ""
}

# Test 2: Exception Mapping to HTTP Status Codes
if ($TestExceptionMapping) {
    Write-Host "Test 2: Exception Mapping to HTTP Status Codes" -ForegroundColor Yellow
    Write-Host ("=" * 50) -ForegroundColor Gray
    Write-Host ""
    
    # Test cases for different exception types
    $testCases = @(
        @{
            Name = "Validation Error (400)"
            Endpoint = "/api/auth/register"
            Method = "POST"
            Body = @{ email = ""; password = "" } | ConvertTo-Json
            ExpectedStatus = 400
            ExpectedStatusText = "ValidationError"
        },
        @{
            Name = "Not Found (404)"
            Endpoint = "/api/products/999999"
            Method = "GET"
            Body = $null
            ExpectedStatus = 404
            ExpectedStatusText = "NotFound"
        }
    )
    
    foreach ($testCase in $testCases) {
        Write-Host "Testing: $($testCase.Name)" -ForegroundColor Green
        try {
            $headers = @{
                "Content-Type" = "application/json"
            }
            
            if ($testCase.Body) {
                $response = Invoke-WebRequest -Uri "$BaseUrl$($testCase.Endpoint)" `
                    -Method $testCase.Method `
                    -Headers $headers `
                    -Body $testCase.Body `
                    -ErrorAction Stop
            } else {
                $response = Invoke-WebRequest -Uri "$BaseUrl$($testCase.Endpoint)" `
                    -Method $testCase.Method `
                    -Headers $headers `
                    -ErrorAction Stop
            }
            
            Write-Host "   [FAIL] Request should have failed" -ForegroundColor Red
        } catch {
            $httpError = $_.Exception.Response
            if ($httpError) {
                $statusCode = $httpError.StatusCode.value__
                $reader = New-Object System.IO.StreamReader($httpError.GetResponseStream())
                $responseBody = $reader.ReadToEnd()
                $jsonResponse = $responseBody | ConvertFrom-Json
                
                if ($statusCode -eq $testCase.ExpectedStatus) {
                    Write-Host "   [OK] Correct HTTP status code: $statusCode" -ForegroundColor Green
                } else {
                    Write-Host "   [FAIL] Expected status $($testCase.ExpectedStatus), got $statusCode" -ForegroundColor Red
                }
                
                if ($jsonResponse.status -eq $testCase.ExpectedStatusText) {
                    Write-Host "   [OK] Correct status text: $($jsonResponse.status)" -ForegroundColor Green
                } else {
                    Write-Host "   [WARN] Status text: $($jsonResponse.status) (expected: $($testCase.ExpectedStatusText))" -ForegroundColor Yellow
                }
            }
        }
        Write-Host ""
    }
}

# Test 3: ApiResponse Format Consistency
if ($TestApiResponse) {
    Write-Host "Test 3: ApiResponse Format Consistency" -ForegroundColor Yellow
    Write-Host ("=" * 50) -ForegroundColor Gray
    Write-Host ""
    
    try {
        # Make a request that will fail
        $response = Invoke-WebRequest -Uri "$BaseUrl/api/invalid-endpoint" `
            -Method GET `
            -ErrorAction Stop
        
        Write-Host "   [FAIL] Request should have failed" -ForegroundColor Red
    } catch {
        $httpError = $_.Exception.Response
        if ($httpError) {
            $reader = New-Object System.IO.StreamReader($httpError.GetResponseStream())
            $responseBody = $reader.ReadToEnd()
            $jsonResponse = $responseBody | ConvertFrom-Json
            
            Write-Host "Checking ApiResponse format..." -ForegroundColor Gray
            Write-Host ""
            
            $checks = @(
                @{ Property = "isSuccessful"; Expected = $false },
                @{ Property = "status"; Expected = $null },
                @{ Property = "statusReason"; Expected = $null },
                @{ Property = "data"; Expected = $null }
            )
            
            $allPassed = $true
            foreach ($check in $checks) {
                $property = $check.Property
                if ($jsonResponse.PSObject.Properties.Name -contains $property) {
                    Write-Host "   [OK] Property '$property' exists" -ForegroundColor Green
                } else {
                    Write-Host "   [FAIL] Property '$property' missing" -ForegroundColor Red
                    $allPassed = $false
                }
            }
            
            if ($jsonResponse.data -and $jsonResponse.data.correlationId) {
                Write-Host "   [OK] Correlation ID in data object" -ForegroundColor Green
            } else {
                Write-Host "   [FAIL] Correlation ID missing in data object" -ForegroundColor Red
                $allPassed = $false
            }
            
            if ($jsonResponse.data -and $jsonResponse.data.timestamp) {
                Write-Host "   [OK] Timestamp in data object" -ForegroundColor Green
            } else {
                Write-Host "   [WARN] Timestamp missing in data object" -ForegroundColor Yellow
            }
            
            if ($allPassed) {
                Write-Host ""
                Write-Host "   [OK] ApiResponse format is consistent!" -ForegroundColor Green
            }
        }
    }
    Write-Host ""
}

# Test 4: Security - No Internal Details Exposed
if ($TestSecurity) {
    Write-Host "Test 4: Security - No Internal Details Exposed" -ForegroundColor Yellow
    Write-Host ("=" * 50) -ForegroundColor Gray
    Write-Host ""
    
    try {
        # Make a request that will cause an exception
        $response = Invoke-WebRequest -Uri "$BaseUrl/api/invalid-endpoint" `
            -Method GET `
            -ErrorAction Stop
        
        Write-Host "   [FAIL] Request should have failed" -ForegroundColor Red
    } catch {
        $httpError = $_.Exception.Response
        if ($httpError) {
            $reader = New-Object System.IO.StreamReader($httpError.GetResponseStream())
            $responseBody = $reader.ReadToEnd()
            $jsonResponse = $responseBody | ConvertFrom-Json
            
            Write-Host "Checking for internal details..." -ForegroundColor Gray
            Write-Host ""
            
            # Check if stack trace is exposed (should only be in development)
            if ($jsonResponse.data.stackTrace) {
                Write-Host "   [WARN] Stack trace found in response (OK in development, should not be in production)" -ForegroundColor Yellow
            } else {
                Write-Host "   [OK] Stack trace not exposed (correct for production)" -ForegroundColor Green
            }
            
            # Check if inner exception is exposed
            if ($jsonResponse.data.innerException) {
                Write-Host "   [WARN] Inner exception found in response (OK in development, should not be in production)" -ForegroundColor Yellow
            } else {
                Write-Host "   [OK] Inner exception not exposed (correct for production)" -ForegroundColor Green
            }
            
            # Check if statusReason is user-friendly (not technical)
            if ($jsonResponse.statusReason) {
                $technicalTerms = @("System.", "Exception", "at ", "StackTrace", "InnerException")
                $hasTechnicalTerms = $false
                foreach ($term in $technicalTerms) {
                    if ($jsonResponse.statusReason -like "*$term*") {
                        $hasTechnicalTerms = $true
                        break
                    }
                }
                
                if ($hasTechnicalTerms) {
                    Write-Host "   [WARN] Status reason contains technical terms: $($jsonResponse.statusReason)" -ForegroundColor Yellow
                } else {
                    Write-Host "   [OK] Status reason is user-friendly: $($jsonResponse.statusReason)" -ForegroundColor Green
                }
            }
        }
    }
    Write-Host ""
}

Write-Host "=== Testing Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "   1. Check application logs for correlation IDs" -ForegroundColor Gray
Write-Host "   2. Verify error responses in Swagger UI" -ForegroundColor Gray
Write-Host "   3. Test with different exception types" -ForegroundColor Gray
Write-Host "   4. Verify production vs development behavior" -ForegroundColor Gray
Write-Host ""

